language: node_js
node_js:
  - "stable"
cache:
  yarn: true
  directories:
  - node_modules
script:
  - yarn install
  - yarn build:travis

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: main